spring.jpa.hibernate.ddl-auto: validate
spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/diplom?serverTimezone=Europe/Moscow
spring.datasource.username: root
spring.datasource.password: 27526976
hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql: false