/*Первый юзер*/
INSERT INTO posts (id, is_active, moderation_status, text, time, title, view_count, moderator_id, user_id)
VALUES (1, 1, 'ACCEPTED', 'Это <h3>текст(h3)</h3> тестового <b>поста(b)</b>', CURRENT_DATE, 'Заголовок тестового поста', 0, NULL, 1);

/* СТАРИННЫЙ ПОСТ */
INSERT INTO posts (id, is_active, moderation_status, text, time, title, view_count, moderator_id, user_id)
VALUES (2, 1, 'ACCEPTED', 'Этот пост с датой публикации 1988 год', '1988/03/14', 'Заголовок старинного поста', 0, NULL, 1);

/* НЕАКТИВНЫЙ ПОСТ (is_active = 0) */
INSERT INTO posts (id, is_active, moderation_status, text, time, title, view_count, moderator_id, user_id)
VALUES (3, 0, 'NEW', 'Этот пост неактивен (is_active = 0)', CURRENT_TIME, 'Заголовок неактивного поста', 0, NULL, 1);

/* НЕДОПУЩЕННЫЙ ПОСТ (moderationStatus = NEW) */
INSERT INTO posts (id, is_active, moderation_status, text, time, title, view_count, moderator_id, user_id)
VALUES (4, 1, 'NEW', 'Этот пост ещё недопущен (status NEW)', CURRENT_TIME, 'Заголовок недопущенного поста', 0, NULL, 1);

/* ПОСТ С ОТЛОЖЕННОЙ ДАТОЙ ПУБЛИКАЦИИ */
INSERT INTO posts (id, is_active, moderation_status, text, time, title, view_count, moderator_id, user_id)
VALUES (5, 1, 'ACCEPTED', 'Этот пост с датой публикации 2025 год', '2028/03/14', 'Заголовок отложенного поста', 0, NULL, 1);

/* ОТКЛОНЕННЫЙ ПОСТ */
INSERT INTO posts (id, is_active, moderation_status, text, time, title, view_count, moderator_id, user_id)
VALUES (100, 1, 'DECLINED', 'Этот пост отклонён (DECLINED)', '2028/03/14', 'Заголовок отклонённого поста', 0, NULL, 1);

/*Второй юзер*/
INSERT INTO posts VALUES (6, 1, 'ACCEPTED', 'POST #6: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/02', 'Заголовок #6', 0, NULL, 2);
INSERT INTO posts VALUES (7, 1, 'ACCEPTED', 'POST #7: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/18', 'Заголовок #7', 0, NULL, 2);
INSERT INTO posts VALUES (8, 1, 'ACCEPTED', 'POST #8: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/14', 'Заголовок #8', 0, NULL, 2);
INSERT INTO posts VALUES (9, 1, 'ACCEPTED', 'POST #9: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/11', 'Заголовок #9', 0, NULL, 2);
INSERT INTO posts VALUES (10, 1, 'ACCEPTED', 'POST #10: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/13', 'Заголовок #10', 0, NULL, 2);
INSERT INTO posts VALUES (11, 1, 'ACCEPTED', 'POST #11: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/23', 'Заголовок #11', 0, NULL, 2);
INSERT INTO posts VALUES (12, 1, 'ACCEPTED', 'POST #12: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/02', 'Заголовок #12', 0, NULL, 2);
INSERT INTO posts VALUES (13, 1, 'ACCEPTED', 'POST #13: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/18', 'Заголовок #13', 0, NULL, 2);
INSERT INTO posts VALUES (14, 1, 'ACCEPTED', 'POST #14: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/17', 'Заголовок #14', 0, NULL, 2);
INSERT INTO posts VALUES (15, 1, 'ACCEPTED', 'POST #15: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/21', 'Заголовок #15', 0, NULL, 2);
INSERT INTO posts VALUES (16, 1, 'ACCEPTED', 'POST #16: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/22', 'Заголовок #16', 0, NULL, 2);
INSERT INTO posts VALUES (17, 1, 'ACCEPTED', 'POST #17: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/09', 'Заголовок #17', 0, NULL, 2);
INSERT INTO posts VALUES (18, 1, 'ACCEPTED', 'POST #18: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/02', 'Заголовок #18', 0, NULL, 2);
INSERT INTO posts VALUES (19, 1, 'ACCEPTED', 'POST #19: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/23', 'Заголовок #19', 0, NULL, 2);
INSERT INTO posts VALUES (20, 1, 'ACCEPTED', 'POST #20: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/22', 'Заголовок #20', 0, NULL, 2);
INSERT INTO posts VALUES (21, 1, 'ACCEPTED', 'POST #21: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/09', 'Заголовок #21', 0, NULL, 2);
INSERT INTO posts VALUES (22, 1, 'ACCEPTED', 'POST #22: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/14', 'Заголовок #22', 0, NULL, 2);
INSERT INTO posts VALUES (23, 1, 'ACCEPTED', 'POST #23: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/02', 'Заголовок #23', 0, NULL, 2);
INSERT INTO posts VALUES (24, 1, 'ACCEPTED', 'POST #24: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/16', 'Заголовок #24', 0, NULL, 2);
INSERT INTO posts VALUES (25, 1, 'ACCEPTED', 'POST #25: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/17', 'Заголовок #25', 0, NULL, 2);
INSERT INTO posts VALUES (26, 1, 'ACCEPTED', 'POST #26: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/09', 'Заголовок #26', 0, NULL, 2);
INSERT INTO posts VALUES (27, 1, 'ACCEPTED', 'POST #27: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/01', 'Заголовок #27', 0, NULL, 2);
INSERT INTO posts VALUES (28, 1, 'ACCEPTED', 'POST #28: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/09', 'Заголовок #28', 0, NULL, 2);
INSERT INTO posts VALUES (29, 1, 'ACCEPTED', 'POST #29: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/22', 'Заголовок #29', 0, NULL, 2);
INSERT INTO posts VALUES (30, 1, 'ACCEPTED', 'POST #30: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/25', 'Заголовок #30', 0, NULL, 2);
INSERT INTO posts VALUES (31, 1, 'ACCEPTED', 'POST #31: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/06', 'Заголовок #31', 0, NULL, 2);
INSERT INTO posts VALUES (32, 1, 'ACCEPTED', 'POST #32: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/20', 'Заголовок #32', 0, NULL, 2);
INSERT INTO posts VALUES (33, 1, 'ACCEPTED', 'POST #33: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/11', 'Заголовок #33', 0, NULL, 2);
INSERT INTO posts VALUES (34, 1, 'ACCEPTED', 'POST #34: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/17', 'Заголовок #34', 0, NULL, 2);
INSERT INTO posts VALUES (35, 1, 'ACCEPTED', 'POST #35: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/11', 'Заголовок #35', 0, NULL, 2);
INSERT INTO posts VALUES (36, 1, 'ACCEPTED', 'POST #36: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/24', 'Заголовок #36', 0, NULL, 2);
INSERT INTO posts VALUES (37, 1, 'ACCEPTED', 'POST #37: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/23', 'Заголовок #37', 0, NULL, 2);
INSERT INTO posts VALUES (38, 1, 'ACCEPTED', 'POST #38: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/14', 'Заголовок #38', 0, NULL, 2);
INSERT INTO posts VALUES (39, 1, 'ACCEPTED', 'POST #39: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/04', 'Заголовок #39', 0, NULL, 2);
INSERT INTO posts VALUES (40, 1, 'ACCEPTED', 'POST #40: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/19', 'Заголовок #40', 0, NULL, 2);
INSERT INTO posts VALUES (41, 1, 'ACCEPTED', 'POST #41: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/27', 'Заголовок #41', 0, NULL, 2);
INSERT INTO posts VALUES (42, 1, 'ACCEPTED', 'POST #42: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/14', 'Заголовок #42', 0, NULL, 2);
INSERT INTO posts VALUES (43, 1, 'ACCEPTED', 'POST #43: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/04', 'Заголовок #43', 0, NULL, 2);
INSERT INTO posts VALUES (44, 1, 'ACCEPTED', 'POST #44: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/24', 'Заголовок #44', 0, NULL, 2);
INSERT INTO posts VALUES (45, 1, 'ACCEPTED', 'POST #45: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/04', 'Заголовок #45', 0, NULL, 2);
INSERT INTO posts VALUES (46, 1, 'ACCEPTED', 'POST #46: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/12', 'Заголовок #46', 0, NULL, 2);
INSERT INTO posts VALUES (47, 1, 'ACCEPTED', 'POST #47: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/17', 'Заголовок #47', 0, NULL, 2);
INSERT INTO posts VALUES (48, 1, 'ACCEPTED', 'POST #48: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/19', 'Заголовок #48', 0, NULL, 2);
INSERT INTO posts VALUES (49, 1, 'ACCEPTED', 'POST #49: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/17', 'Заголовок #49', 0, NULL, 2);
INSERT INTO posts VALUES (50, 1, 'ACCEPTED', 'POST #50: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/18', 'Заголовок #50', 0, NULL, 2);
INSERT INTO posts VALUES (51, 1, 'ACCEPTED', 'POST #51: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/06', 'Заголовок #51', 0, NULL, 2);
INSERT INTO posts VALUES (52, 1, 'ACCEPTED', 'POST #52: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/27', 'Заголовок #52', 0, NULL, 2);
INSERT INTO posts VALUES (53, 1, 'ACCEPTED', 'POST #53: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/27', 'Заголовок #53', 0, NULL, 2);
INSERT INTO posts VALUES (54, 1, 'ACCEPTED', 'POST #54: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/16', 'Заголовок #54', 0, NULL, 2);
INSERT INTO posts VALUES (55, 1, 'ACCEPTED', 'POST #55: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/07', 'Заголовок #55', 0, NULL, 2);
INSERT INTO posts VALUES (56, 1, 'ACCEPTED', 'POST #56: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/23', 'Заголовок #56', 0, NULL, 2);
INSERT INTO posts VALUES (57, 1, 'ACCEPTED', 'POST #57: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/08', 'Заголовок #57', 0, NULL, 2);
INSERT INTO posts VALUES (58, 1, 'ACCEPTED', 'POST #58: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/27', 'Заголовок #58', 0, NULL, 2);
INSERT INTO posts VALUES (59, 1, 'ACCEPTED', 'POST #59: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/05', 'Заголовок #59', 0, NULL, 2);
INSERT INTO posts VALUES (60, 1, 'ACCEPTED', 'POST #60: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/15', 'Заголовок #60', 0, NULL, 2);
INSERT INTO posts VALUES (61, 1, 'ACCEPTED', 'POST #61: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/26', 'Заголовок #61', 0, NULL, 2);
INSERT INTO posts VALUES (62, 1, 'ACCEPTED', 'POST #62: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/01', 'Заголовок #62', 0, NULL, 2);
INSERT INTO posts VALUES (63, 1, 'ACCEPTED', 'POST #63: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/14', 'Заголовок #63', 0, NULL, 2);
INSERT INTO posts VALUES (64, 1, 'ACCEPTED', 'POST #64: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/01', 'Заголовок #64', 0, NULL, 2);
INSERT INTO posts VALUES (65, 1, 'ACCEPTED', 'POST #65: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/07', 'Заголовок #65', 0, NULL, 2);
INSERT INTO posts VALUES (66, 1, 'ACCEPTED', 'POST #66: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/15', 'Заголовок #66', 0, NULL, 2);
INSERT INTO posts VALUES (67, 1, 'ACCEPTED', 'POST #67: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/24', 'Заголовок #67', 0, NULL, 2);
INSERT INTO posts VALUES (68, 1, 'ACCEPTED', 'POST #68: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/09', 'Заголовок #68', 0, NULL, 2);
INSERT INTO posts VALUES (69, 1, 'ACCEPTED', 'POST #69: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/27', 'Заголовок #69', 0, NULL, 2);
INSERT INTO posts VALUES (70, 1, 'ACCEPTED', 'POST #70: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/17', 'Заголовок #70', 0, NULL, 2);
INSERT INTO posts VALUES (71, 1, 'ACCEPTED', 'POST #71: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/14', 'Заголовок #71', 0, NULL, 2);
INSERT INTO posts VALUES (72, 1, 'ACCEPTED', 'POST #72: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/13', 'Заголовок #72', 0, NULL, 2);
INSERT INTO posts VALUES (73, 1, 'ACCEPTED', 'POST #73: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/09', 'Заголовок #73', 0, NULL, 2);
INSERT INTO posts VALUES (74, 1, 'ACCEPTED', 'POST #74: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/13', 'Заголовок #74', 0, NULL, 2);
INSERT INTO posts VALUES (75, 1, 'ACCEPTED', 'POST #75: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/09', 'Заголовок #75', 0, NULL, 2);
INSERT INTO posts VALUES (76, 1, 'ACCEPTED', 'POST #76: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/27', 'Заголовок #76', 0, NULL, 2);
INSERT INTO posts VALUES (77, 1, 'ACCEPTED', 'POST #77: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/21', 'Заголовок #77', 0, NULL, 2);
INSERT INTO posts VALUES (78, 1, 'ACCEPTED', 'POST #78: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/12', 'Заголовок #78', 0, NULL, 2);
INSERT INTO posts VALUES (79, 1, 'ACCEPTED', 'POST #79: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/18', 'Заголовок #79', 0, NULL, 2);
INSERT INTO posts VALUES (80, 1, 'ACCEPTED', 'POST #80: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/02', 'Заголовок #80', 0, NULL, 2);
INSERT INTO posts VALUES (81, 1, 'ACCEPTED', 'POST #81: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/12', 'Заголовок #81', 0, NULL, 2);
INSERT INTO posts VALUES (82, 1, 'ACCEPTED', 'POST #82: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/25', 'Заголовок #82', 0, NULL, 2);
INSERT INTO posts VALUES (83, 1, 'ACCEPTED', 'POST #83: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/26', 'Заголовок #83', 0, NULL, 2);
INSERT INTO posts VALUES (84, 1, 'ACCEPTED', 'POST #84: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/02', 'Заголовок #84', 0, NULL, 2);
INSERT INTO posts VALUES (85, 1, 'ACCEPTED', 'POST #85: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/21', 'Заголовок #85', 0, NULL, 2);
INSERT INTO posts VALUES (86, 1, 'ACCEPTED', 'POST #86: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/25', 'Заголовок #86', 0, NULL, 2);
INSERT INTO posts VALUES (87, 1, 'ACCEPTED', 'POST #87: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/15', 'Заголовок #87', 0, NULL, 2);
INSERT INTO posts VALUES (88, 1, 'ACCEPTED', 'POST #88: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/05', 'Заголовок #88', 0, NULL, 2);
INSERT INTO posts VALUES (89, 1, 'ACCEPTED', 'POST #89: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/14', 'Заголовок #89', 0, NULL, 2);
INSERT INTO posts VALUES (90, 1, 'ACCEPTED', 'POST #90: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/22', 'Заголовок #90', 0, NULL, 2);
INSERT INTO posts VALUES (91, 1, 'ACCEPTED', 'POST #91: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/25', 'Заголовок #91', 0, NULL, 2);
INSERT INTO posts VALUES (92, 1, 'ACCEPTED', 'POST #92: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/17', 'Заголовок #92', 0, NULL, 2);
INSERT INTO posts VALUES (93, 1, 'ACCEPTED', 'POST #93: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/15', 'Заголовок #93', 0, NULL, 2);
INSERT INTO posts VALUES (94, 1, 'ACCEPTED', 'POST #94: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/01', 'Заголовок #94', 0, NULL, 2);
INSERT INTO posts VALUES (95, 1, 'ACCEPTED', 'POST #95: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/10', 'Заголовок #95', 0, NULL, 2);
INSERT INTO posts VALUES (96, 1, 'ACCEPTED', 'POST #96: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/22', 'Заголовок #96', 0, NULL, 2);
INSERT INTO posts VALUES (97, 1, 'ACCEPTED', 'POST #97: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/01', 'Заголовок #97', 0, NULL, 2);
INSERT INTO posts VALUES (98, 1, 'ACCEPTED', 'POST #98: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/20', 'Заголовок #98', 0, NULL, 2);
INSERT INTO posts VALUES (99, 1, 'ACCEPTED', 'POST #99: text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text', '2021/01/10', 'Заголовок #99', 0, NULL, 2);
